/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Button from "./Button";

interface HeaderProps {
  links: string[];
}

const Header: React.FC<HeaderProps> = ({ links }) => {
  return (
    <header className="flex relative flex-col items-center pb-28 w-full min-h-[491px] max-md:pb-24 max-md:max-w-full">
      <img
        loading="lazy"
        src="https://cdn.builder.io/api/v1/image/assets/TEMP/51f3959d6ec6eb25a028945413ac8aff50d901f9b1b584d34080538bf6fe4f55?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11"
        alt=""
        className="object-cover absolute inset-0 size-full"
      />
      <nav className="flex relative flex-col justify-center items-center self-stretch px-16 py-3 w-full text-base bg-neutral-900 max-md:px-5 max-md:max-w-full">
        <div className="flex flex-wrap gap-10 w-full max-w-[1157px] max-md:max-w-full">
          <div className="flex flex-wrap flex-auto gap-7 text-white whitespace-nowrap max-md:max-w-full">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/0c4bc369c732b4bf6c2901ab1bca691d6d2e06d1de98a4dfca45c66314e542b8?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11"
              alt="Company logo"
              className="object-contain shrink-0 aspect-square w-[71px]"
            />
            <div className="flex flex-wrap flex-auto gap-10 items-start px-48 my-auto max-md:px-5 max-md:max-w-full">
              {links.map((link, index) => (
                <a key={index} href="#" className="text-white">
                  {link}
                </a>
              ))}
            </div>
          </div>
          <Button variant="outline">Contact Us</Button>
        </div>
      </nav>
      <h1 className="relative mt-28 text-7xl font-semibold tracking-tighter leading-none text-center text-white max-md:mt-10 max-md:max-w-full max-md:text-4xl">
        Upload Portfolio
      </h1>
      <p className="relative mt-10 mb-0 text-xl leading-8 text-center text-white w-[527px] max-md:mb-2.5 max-md:max-w-full">
        Lorem Ipsum is simply dummy text of the printing and typesetting
        industry. Lorem Ipsum has
      </p>
    </header>
  );
};

export default Header;
