/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Button from "./Button";

const UploadForm: React.FC = () => {
  return (
    <form className="flex flex-col w-full text-sm font-medium max-md:mt-10 max-md:max-w-full">
      <h2 className="self-start text-4xl font-semibold leading-none text-zinc-800">
        Upload a New Portfolio
      </h2>
      <p className="self-start mt-3 text-sm leading-5 text-black max-md:max-w-full">
        There are many variations of passages of Lorem Ipsum available, but the
        majority have suffered alteration in some form.
      </p>
      <div className="mt-16 max-md:mt-10">
        <label htmlFor="title" className="text-red-600">
          Title <span className="text-red-600">*</span>
        </label>
        <input
          id="title"
          type="text"
          className="flex overflow-hidden gap-2 items-center px-4 py-3 mt-1.5 w-full font-light leading-6 text-black bg-white border-gray-300 border-solid shadow-sm border-[0.91px]"
          placeholder="joe smith"
        />
      </div>
      <div className="mt-6">
        <label htmlFor="category" className="text-red-600">
          Category <span className="text-red-600">*</span>
        </label>
        <input
          id="category"
          type="text"
          className="flex overflow-hidden gap-2 items-center px-4 py-3 mt-1.5 w-full font-light leading-6 text-black bg-white border-gray-300 border-solid shadow-sm border-[0.91px]"
          placeholder="joe smith"
        />
      </div>
      <div className="mt-4">
        <label htmlFor="tags" className="text-red-600">
          Search Tags <span className="text-red-600">*</span>
        </label>
        <input
          id="tags"
          type="text"
          className="flex overflow-hidden gap-2 items-center px-4 py-3 mt-1.5 w-full font-light leading-6 text-black bg-white border-gray-300 border-solid shadow-sm border-[0.91px]"
          placeholder="joe smith"
        />
      </div>
      <div className="mt-6">
        <label htmlFor="description" className="text-red-600">
          Description <span className="text-red-600">*</span>
        </label>
        <textarea
          id="description"
          className="flex overflow-hidden gap-2 items-center px-4 pt-2.5 pb-28 mt-1.5 w-full font-light leading-6 text-black bg-white border-gray-300 border-solid shadow-sm border-[0.91px] min-h-[150px] max-md:pb-24"
          placeholder="joe smith"
        ></textarea>
      </div>
      <p className="mt-4 text-sm leading-5 text-black max-md:max-w-full">
        There are many variations of passages of Lorem Ipsum available, but the
        majority have suffered alteration in some form.
      </p>
      <div className="flex flex-wrap gap-5 justify-between mt-8 text-base text-center max-md:max-w-full">
        <Button variant="outline">cancel</Button>
        <Button>Upload portfolio +</Button>
      </div>
    </form>
  );
};

export default UploadForm;
