/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import Hero from "./Hero";
import Portfolio from "./Portfolio";
import WhatWeDo from "./WhatWeDo";
import Footer from "./Footer";

const App: React.FC = () => {
  return (
    <div className="flex overflow-hidden flex-col bg-white">
      <Header logo="https://cdn.builder.io/api/v1/image/assets/TEMP/0c4bc369c732b4bf6c2901ab1bca691d6d2e06d1de98a4dfca45c66314e542b8?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11" />
      <main>
        <Hero
          backgroundImage="https://cdn.builder.io/api/v1/image/assets/TEMP/51f3959d6ec6eb25a028945413ac8aff50d901f9b1b584d34080538bf6fe4f55?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11"
          title="Upload Portfolio"
          description="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has"
        />
        <Portfolio />
        <WhatWeDo
          title="What we are Doing"
          description="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna enim, quis nostrud laboris."
          bulletPoints={[
            "Lorem ipsum dolor sit amet, consectetu",
            "Lorem ipsum dolor",
            "Lorem ipsum dolor sit",
          ]}
          image="https://cdn.builder.io/api/v1/image/assets/TEMP/7b7177ee7be56471d98d61c3f7daed83b05924e2464a158d3d5e1a9b11ac208d?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11"
        />
      </main>
      <Footer description="We make sure to give your car the pempering it deserves in BubBlast." />
    </div>
  );
};

export default App;
