/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
import PortfolioFilter from "./PortfolioFilter";
import PortfolioGrid from "./PortfolioGrid";

interface PortfolioItem {
  image: string;
  category: string;
  title: string;
  description: string;
}

const portfolioItems: PortfolioItem[] = [
  {
    image:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/f9aa3ee1414819fae862bbb888fa9b97f84eeeac9078b3490c1d6d402ae9af63?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11",
    category: "Interior Detailing",
    title: "Interior Detailing",
    description:
      "a cleaning of the inner parts of a vehicle including leather, ....",
  },
  // ... repeat for all 8 items
];

const filters = [
  { label: "All", isActive: true },
  { label: "Interior Detailing", isActive: false },
  { label: "Exterior Wash", isActive: false },
  { label: "Wheel & Tire Cleaning", isActive: false },
  { label: "Hand Waxing", isActive: false },
];

const Portfolio: React.FC = () => {
  const [activeFilter, setActiveFilter] = useState("All");

  const handleFilterClick = (label: string) => {
    setActiveFilter(label);
  };

  const filteredItems =
    activeFilter === "All"
      ? portfolioItems
      : portfolioItems.filter((item) => item.category === activeFilter);

  return (
    <section className="flex flex-col px-20 mt-9 w-full max-md:px-5 max-md:max-w-full">
      <h2 className="self-start text-4xl font-semibold leading-none text-zinc-800">
        Portfolio
      </h2>
      <PortfolioFilter
        filters={filters.map((f) => ({
          ...f,
          isActive: f.label === activeFilter,
        }))}
        onFilterClick={handleFilterClick}
      />
      <PortfolioGrid items={filteredItems} />
    </section>
  );
};

export default Portfolio;
