/**
 * This code was generated by Builder.io.
 */
import React from "react";
import PortfolioItem from "./PortfolioItem";

interface PortfolioItemData {
  image: string;
  category: string;
  title: string;
  description: string;
}

interface PortfolioGridProps {
  items: PortfolioItemData[];
}

const PortfolioGrid: React.FC<PortfolioGridProps> = ({ items }) => {
  return (
    <div className="mt-20 max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        {items.map((item, index) => (
          <div
            key={index}
            className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full"
          >
            <PortfolioItem {...item} />
          </div>
        ))}
      </div>
    </div>
  );
};

export default PortfolioGrid;
