/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface PortfolioItemProps {
  image: string;
  category: string;
  title: string;
  description: string;
}

const PortfolioItem: React.FC<PortfolioItemProps> = ({
  image,
  category,
  title,
  description,
}) => {
  return (
    <div className="flex flex-col grow items-start text-blue-400 max-md:mt-10">
      <img
        loading="lazy"
        src={image}
        alt={title}
        className="object-contain self-stretch w-full rounded-md aspect-[1.43]"
      />
      <div className="px-5 py-2 mt-3 text-xs leading-3 rounded-xl border border-blue-400 border-solid bg-blue-400 bg-opacity-30 max-md:pl-5">
        {category}
      </div>
      <h3 className="text-xl font-semibold leading-10 text-zinc-800">
        {title}
      </h3>
      <p className="text-base leading-6 opacity-50 text-zinc-800">
        {description}
      </p>
      <a href="#" className="mt-6 text-base font-medium text-center">
        View Now
      </a>
    </div>
  );
};

export default PortfolioItem;
