/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface FilterItem {
  label: string;
  isActive: boolean;
}

interface PortfolioFilterProps {
  filters: FilterItem[];
  onFilterClick: (label: string) => void;
}

const PortfolioFilter: React.FC<PortfolioFilterProps> = ({
  filters,
  onFilterClick,
}) => {
  return (
    <div className="flex flex-wrap gap-4 self-start mt-5 text-base font-medium text-center text-zinc-500">
      {filters.map((filter, index) => (
        <button
          key={index}
          onClick={() => onFilterClick(filter.label)}
          className={`px-8 py-3 rounded-[136px] max-md:px-5 ${
            filter.isActive
              ? "text-white capitalize whitespace-nowrap bg-blue-400"
              : "border border-blue-400 border-solid"
          }`}
        >
          {filter.label}
        </button>
      ))}
    </div>
  );
};

export default PortfolioFilter;
