/**
 * This code was generated by Builder.io.
 */
import React from "react";

interface WhatWeDoProps {
  title: string;
  description: string;
  bulletPoints: string[];
  image: string;
}

const WhatWeDo: React.FC<WhatWeDoProps> = ({
  title,
  description,
  bulletPoints,
  image,
}) => {
  return (
    <section className="pl-20 mt-24 w-full bg-neutral-900 max-md:pl-5 max-md:mt-10 max-md:max-w-full">
      <div className="flex gap-5 max-md:flex-col">
        <div className="flex flex-col w-[31%] max-md:ml-0 max-md:w-full">
          <div className="flex flex-col items-start self-stretch my-auto w-full font-bold max-md:mt-10">
            <h2 className="text-5xl leading-10 text-stone-50">{title}</h2>
            <div className="flex flex-col items-start self-stretch pl-2 mt-8 text-sm leading-6 text-neutral-400">
              <div className="shrink-0 border-blue-400 border-solid border-[3px] h-[3px] w-[132px]" />
              <p className="self-stretch mt-5">{description}</p>
              <ul className="mt-10">
                {bulletPoints.map((point, index) => (
                  <li key={index} className="mt-1.5 max-md:ml-2.5">
                    {point}
                  </li>
                ))}
              </ul>
            </div>
            <div className="flex gap-4 mt-11 w-full text-base text-white max-md:mt-10">
              <a
                href="#more"
                className="self-stretch px-8 py-2.5 bg-blue-400 rounded-[100px] max-md:px-5"
              >
                See More
              </a>
              <a
                href="#contact"
                className="self-stretch px-8 py-2.5 border border-blue-400 border-solid rounded-[100px] max-md:px-5"
              >
                Contact Us
              </a>
            </div>
          </div>
        </div>
        <div className="flex flex-col ml-5 w-[69%] max-md:ml-0 max-md:w-full">
          <img
            loading="lazy"
            src={image}
            alt="What we do illustration"
            className="object-contain grow w-full aspect-[1.14] max-md:mt-10 max-md:max-w-full"
          />
        </div>
      </div>
    </section>
  );
};

export default WhatWeDo;
