/**
 * This code was generated by Builder.io.
 */
import React from "react";
import MainContent from "./MainContent";

const App: React.FC = () => {
  return (
    <div className="App">
      <MainContent />
    </div>
  );
};

export default App;
