/**
 * This code was generated by Builder.io.
 */
import React from "react";
import Header from "./Header";
import PortfolioSection from "./PortfolioSection";
import WhatWeDoSection from "./WhatWeDoSection";
import Footer from "./Footer";

const MainContent: React.FC = () => {
  const handleContactClick = () => {
    // Implement contact functionality
    console.log("Contact button clicked");
  };

  return (
    <div className="flex overflow-hidden flex-col bg-white">
      <Header onContactClick={handleContactClick} />
      <main>
        <PortfolioSection />
        <WhatWeDoSection />
      </main>
      <Footer />
    </div>
  );
};

export default MainContent;
