/**
 * This code was generated by Builder.io.
 */
import React from "react";
import PortfolioItem from "./PortfolioItem";

interface PortfolioData {
  id: number;
  thumbnail: string;
  title: string;
  description: string;
  date: string;
  type: string;
}

const portfolioData: PortfolioData[] = [
  {
    id: 1,
    thumbnail:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/f4be65c2c43f24aeca38420b0911bf99e5519dceb776f785ecba7449de76c1f9?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11",
    title: "There are many variations of passages",
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
    date: "8/28/2024",
    type: "Images",
  },
  {
    id: 2,
    thumbnail:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/f4be65c2c43f24aeca38420b0911bf99e5519dceb776f785ecba7449de76c1f9?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11",
    title: "There are many variations of passages",
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
    date: "8/28/2024",
    type: "Images",
  },
  {
    id: 3,
    thumbnail:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/f4be65c2c43f24aeca38420b0911bf99e5519dceb776f785ecba7449de76c1f9?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11",
    title: "There are many variations of passages",
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
    date: "8/28/2024",
    type: "Images",
  },
  {
    id: 4,
    thumbnail:
      "https://cdn.builder.io/api/v1/image/assets/TEMP/f4be65c2c43f24aeca38420b0911bf99e5519dceb776f785ecba7449de76c1f9?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11",
    title: "There are many variations of passages",
    description:
      "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
    date: "8/28/2024",
    type: "Images",
  },
];

const PortfolioSection: React.FC = () => {
  return (
    <section className="flex flex-col px-20 mt-20 w-full max-md:px-5 max-md:mt-10 max-md:max-w-full">
      <div className="flex flex-wrap gap-5 justify-between w-full max-md:max-w-full">
        <h2 className="my-auto text-4xl font-semibold leading-none text-zinc-800">
          Portfolio
        </h2>
        <div className="flex flex-wrap gap-4 text-base font-medium text-center">
          <div className="flex gap-1.5 my-auto text-gray-500">
            <div className="grow">Most viewed</div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/ce5a00058648a6fdfc5de60f9b20a98b2b163667cd3c0b35b4a323a9bc317ceb?placeholderIfAbsent=true&apiKey=a9e86b264a2b427cb02fa9112891bf11"
              alt=""
              className="object-contain shrink-0 my-auto w-1.5 aspect-[1.5]"
            />
          </div>
          <div className="flex flex-auto gap-5 max-md:max-w-full">
            <button className="px-7 py-3 text-gray-500 whitespace-nowrap border border-gray-500 border-solid rounded-[136px] max-md:px-5">
              Search
            </button>
            <button className="px-11 py-3 text-white capitalize bg-blue-400 rounded-[136px] max-md:px-5">
              Upload portfolio +
            </button>
          </div>
        </div>
      </div>
      <div className="flex flex-col pb-12 mt-16 w-full text-black rounded-xl border border-black border-solid max-md:mt-10 max-md:max-w-full">
        <div className="flex flex-wrap gap-5 justify-between py-1.5 pr-20 pl-3.5 w-full text-xl leading-10 text-center whitespace-nowrap rounded-xl bg-zinc-300 text-zinc-400 max-md:pr-5 max-md:max-w-full">
          <div className="flex gap-10 max-md:max-w-full">
            <div>Sr.No</div>
            <div>Thumbnail</div>
            <div>Description</div>
          </div>
          <div className="flex gap-10">
            <div>Date</div>
            <div>Type</div>
          </div>
        </div>
        {portfolioData.map((item) => (
          <PortfolioItem key={item.id} {...item} />
        ))}
      </div>
      <p className="self-start mt-6 text-sm text-black max-md:max-w-full">
        There are many variations of passages of Lorem Ipsum available, but the
        majority have suffered alteration in some form.
      </p>
    </section>
  );
};

export default PortfolioSection;
